// ─── ACRONYM DATA ──────────────────────────────────────────────
// 83 product/UX/dev acronyms laid out as a periodic table.
// Each entry has a fixed (col, row) position used by table.html.
// Categories map to color tokens in shared/styles.css.

window.ACRONYMS = [
  {
    "a": "MVP",
    "f": "Minimum Viable Product",
    "cat": "core",
    "es": "Versión más básica de un producto que permite validar hipótesis con usuarios reales.",
    "en": "The simplest version of a product that allows validating hypotheses with real users.",
    "url": "https://www.productplan.com/glossary/minimum-viable-product/",
    "col": 0,
    "rowInCol": 0,
    "row": 0
  },
  {
    "a": "PRD",
    "f": "Product Requirements Document",
    "cat": "core",
    "es": "Documento que describe funcionalidades, objetivos y restricciones de un producto.",
    "en": "A document describing a product's features, goals, and constraints.",
    "url": "https://www.productplan.com/glossary/product-requirements-document/",
    "col": 0,
    "rowInCol": 1,
    "row": 1
  },
  {
    "a": "A/B",
    "f": "A/B Testing (Split Testing)",
    "cat": "core",
    "es": "Experimento que compara dos versiones de un elemento para determinar cuál funciona mejor.",
    "en": "An experiment comparing two versions of an element to determine which performs better.",
    "url": "https://www.optimizely.com/optimization-glossary/ab-testing/",
    "col": 0,
    "rowInCol": 2,
    "row": 2
  },
  {
    "a": "PoC",
    "f": "Proof of Concept",
    "cat": "core",
    "es": "Experimento o prototipo temprano para validar la viabilidad técnica o de negocio de una idea.",
    "en": "An early experiment or prototype to validate the technical or business feasibility of an idea.",
    "url": "https://www.productplan.com/glossary/proof-of-concept/",
    "col": 0,
    "rowInCol": 3,
    "row": 3
  },
  {
    "a": "PDCA",
    "f": "Plan, Do, Check, Act",
    "cat": "core",
    "es": "Ciclo de mejora continua de cuatro pasos usado en gestión de calidad y desarrollo de productos.",
    "en": "A four-step continuous improvement cycle used in quality management and product development.",
    "url": "https://asq.org/quality-resources/pdca-cycle",
    "col": 0,
    "rowInCol": 4,
    "row": 4
  },
  {
    "a": "AARRR",
    "f": "Acquisition, Activation, Retention, Referral, Revenue",
    "cat": "metrics",
    "es": "Framework pirata de métricas para medir el ciclo de vida del cliente.",
    "en": "Pirate metrics framework for measuring the full customer lifecycle.",
    "url": "https://www.productplan.com/glossary/aarrr-framework/",
    "col": 1,
    "rowInCol": 0,
    "row": 1
  },
  {
    "a": "NPS",
    "f": "Net Promoter Score",
    "cat": "metrics",
    "es": "Métrica que mide la probabilidad de que usuarios recomienden tu producto.",
    "en": "Metric that measures how likely users are to recommend your product.",
    "url": "https://www.netpromoter.com/know/",
    "col": 1,
    "rowInCol": 1,
    "row": 2
  },
  {
    "a": "KPI",
    "f": "Key Performance Indicator",
    "cat": "metrics",
    "es": "Indicador clave para medir el progreso hacia un objetivo estratégico.",
    "en": "Key metric used to measure progress toward a strategic goal.",
    "url": "https://www.investopedia.com/terms/k/kpi.asp",
    "col": 1,
    "rowInCol": 2,
    "row": 3
  },
  {
    "a": "CTR",
    "f": "Click-Through Rate",
    "cat": "metrics",
    "es": "Porcentaje de usuarios que hacen clic en un elemento respecto al total que lo ven.",
    "en": "The percentage of users who click on an element out of all who see it.",
    "url": "https://support.google.com/google-ads/answer/2615875",
    "col": 1,
    "rowInCol": 3,
    "row": 4
  },
  {
    "a": "MoM",
    "f": "Month-over-Month Growth",
    "cat": "metrics",
    "es": "Tasa de crecimiento comparando un mes con el mes inmediatamente anterior.",
    "en": "Growth rate comparing one month to the immediately preceding month.",
    "url": "https://www.investopedia.com/terms/m/mom.asp",
    "col": 1,
    "rowInCol": 4,
    "row": 5
  },
  {
    "a": "YoY",
    "f": "Year-over-Year Growth",
    "cat": "metrics",
    "es": "Tasa de crecimiento comparando un período con el mismo período del año anterior.",
    "en": "Growth rate comparing a period to the same period in the previous year.",
    "url": "https://www.investopedia.com/terms/y/year-over-year.asp",
    "col": 1,
    "rowInCol": 5,
    "row": 6
  },
  {
    "a": "DAU",
    "f": "Daily Active Users",
    "cat": "metrics",
    "es": "Número de usuarios únicos que interactúan con un producto en un día. Indicador clave de engagement.",
    "en": "Number of unique users who interact with a product on a given day. A key engagement indicator.",
    "url": "https://www.productplan.com/glossary/daily-active-users/",
    "col": 1,
    "rowInCol": 6,
    "row": 7
  },
  {
    "a": "MAU",
    "f": "Monthly Active Users",
    "cat": "metrics",
    "es": "Número de usuarios únicos que interactúan con un producto al menos una vez al mes.",
    "en": "Number of unique users who interact with a product at least once a month.",
    "url": "https://www.productplan.com/glossary/monthly-active-users/",
    "col": 1,
    "rowInCol": 7,
    "row": 8
  },
  {
    "a": "RR",
    "f": "Retention Rate",
    "cat": "metrics",
    "es": "Porcentaje de usuarios que continúan usando el producto después de un período determinado.",
    "en": "Percentage of users who continue using the product after a given period.",
    "url": "https://www.investopedia.com/terms/r/retention-rate.asp",
    "col": 1,
    "rowInCol": 8,
    "row": 9
  },
  {
    "a": "ROI",
    "f": "Return on Investment",
    "cat": "metrics",
    "es": "Medida del beneficio obtenido en relación a la inversión realizada.",
    "en": "Measure of the profit gained relative to the investment made.",
    "url": "https://www.investopedia.com/terms/r/returnoninvestment.asp",
    "col": 2,
    "rowInCol": 0,
    "row": 1
  },
  {
    "a": "CSAT",
    "f": "Customer Satisfaction",
    "cat": "metrics",
    "es": "Métrica que mide la satisfacción directa del cliente tras una interacción.",
    "en": "Metric that measures direct customer satisfaction after an interaction.",
    "url": "https://www.qualtrics.com/experience-management/customer/what-is-csat/",
    "col": 2,
    "rowInCol": 1,
    "row": 2
  },
  {
    "a": "CAC",
    "f": "Customer Acquisition Cost",
    "cat": "metrics",
    "es": "Costo total promedio de adquirir un nuevo cliente.",
    "en": "The average total cost of acquiring a new customer.",
    "url": "https://www.investopedia.com/terms/c/customer-acquisition-cost.asp",
    "col": 2,
    "rowInCol": 2,
    "row": 3
  },
  {
    "a": "CLV",
    "f": "Customer Lifetime Value",
    "cat": "metrics",
    "es": "Valor total que un cliente genera para el negocio durante toda su relación con el producto.",
    "en": "The total value a customer generates for the business throughout their relationship.",
    "url": "https://www.investopedia.com/terms/c/customer-lifetime-value.asp",
    "col": 2,
    "rowInCol": 3,
    "row": 4
  },
  {
    "a": "ARPU",
    "f": "Average Revenue Per User",
    "cat": "metrics",
    "es": "Ingresos promedio generados por cada usuario activo en un período determinado.",
    "en": "The average revenue generated per active user in a given period.",
    "url": "https://www.investopedia.com/terms/a/average-revenue-user-arpu.asp",
    "col": 2,
    "rowInCol": 4,
    "row": 5
  },
  {
    "a": "CR",
    "f": "Conversion Rate",
    "cat": "metrics",
    "es": "Porcentaje de usuarios que completan una acción deseada (compra, registro) del total de visitantes.",
    "en": "Percentage of users who complete a desired action (purchase, sign-up) out of total visitors.",
    "url": "https://www.optimizely.com/optimization-glossary/conversion-rate/",
    "col": 2,
    "rowInCol": 5,
    "row": 6
  },
  {
    "a": "AOV",
    "f": "Average Order Value",
    "cat": "metrics",
    "es": "Valor promedio de cada pedido o transacción realizada en un período de tiempo determinado.",
    "en": "The average value of each order or transaction made in a given time period.",
    "url": "https://www.shopify.com/blog/average-order-value",
    "col": 2,
    "rowInCol": 6,
    "row": 7
  },
  {
    "a": "CPC",
    "f": "Cost per Click",
    "cat": "metrics",
    "es": "Costo que paga un anunciante cada vez que un usuario hace clic en su anuncio.",
    "en": "The cost an advertiser pays each time a user clicks on their ad.",
    "url": "https://support.google.com/google-ads/answer/116495",
    "col": 2,
    "rowInCol": 7,
    "row": 8
  },
  {
    "a": "TAM",
    "f": "Total Addressable Market",
    "cat": "business",
    "es": "Tamaño total del mercado disponible si se capturara el 100% de la demanda.",
    "en": "The total market size available if 100% of demand were captured.",
    "url": "https://www.investopedia.com/terms/t/total-addressable-market.asp",
    "col": 3,
    "rowInCol": 0,
    "row": 2
  },
  {
    "a": "SAM",
    "f": "Serviceable Addressable Market",
    "cat": "business",
    "es": "Segmento del TAM al que el producto puede llegar de forma realista.",
    "en": "The segment of the TAM that the product can realistically reach.",
    "url": "https://www.investopedia.com/terms/s/serviceable-available-market.asp",
    "col": 3,
    "rowInCol": 1,
    "row": 3
  },
  {
    "a": "MRD",
    "f": "Market Requirements Document",
    "cat": "business",
    "es": "Documento que define las necesidades del mercado que un producto debe satisfacer.",
    "en": "A document defining the market needs that a product must satisfy.",
    "url": "https://www.productplan.com/glossary/market-requirements-document/",
    "col": 3,
    "rowInCol": 2,
    "row": 4
  },
  {
    "a": "BRD",
    "f": "Business Requirements Document",
    "cat": "business",
    "es": "Documento que detalla los requerimientos de negocio para un proyecto o producto.",
    "en": "A document detailing the business requirements for a project or product.",
    "url": "https://www.projectmanager.com/blog/business-requirements-document",
    "col": 3,
    "rowInCol": 3,
    "row": 5
  },
  {
    "a": "OKRs",
    "f": "Objectives and Key Results",
    "cat": "business",
    "es": "Framework de metas que conecta objetivos cualitativos con resultados medibles.",
    "en": "A goal-setting framework connecting qualitative objectives to measurable results.",
    "url": "https://www.whatmatters.com/faqs/okr-meaning-definition-example",
    "col": 3,
    "rowInCol": 4,
    "row": 6
  },
  {
    "a": "SWOT",
    "f": "Strengths, Weaknesses, Opportunities, Threats",
    "cat": "business",
    "es": "Análisis estratégico de factores internos y externos de un producto o empresa.",
    "en": "A strategic analysis of internal and external factors affecting a product or company.",
    "url": "https://www.investopedia.com/terms/s/swot.asp",
    "col": 3,
    "rowInCol": 5,
    "row": 7
  },
  {
    "a": "SEO",
    "f": "Search Engine Optimization",
    "cat": "business",
    "es": "Técnicas para mejorar la visibilidad de un sitio en motores de búsqueda y atraer tráfico orgánico.",
    "en": "Techniques for improving a site's visibility in search engines and attracting organic traffic.",
    "url": "https://moz.com/learn/seo/what-is-seo",
    "col": 3,
    "rowInCol": 6,
    "row": 8
  },
  {
    "a": "GTM",
    "f": "Go to Market",
    "cat": "business",
    "es": "Estrategia que define cómo un producto llega a sus clientes objetivo, incluyendo canales y posicionamiento.",
    "en": "A strategy defining how a product reaches its target customers, including channels and positioning.",
    "url": "https://www.productplan.com/glossary/go-to-market-strategy/",
    "col": 3,
    "rowInCol": 7,
    "row": 9
  },
  {
    "a": "DACI",
    "f": "Driver, Approver, Contributors, Informed",
    "cat": "business",
    "es": "Framework que define roles claros para la toma de decisiones en equipo.",
    "en": "A framework that defines clear roles for team decision-making.",
    "url": "https://www.atlassian.com/team-playbook/plays/daci",
    "col": 3,
    "rowInCol": 8,
    "row": 10
  },
  {
    "a": "RFP",
    "f": "Request for Proposal",
    "cat": "business",
    "es": "Documento formal que invita a proveedores a presentar propuestas para cubrir una necesidad de proyecto.",
    "en": "A formal document inviting vendors to submit proposals to meet a specific project need.",
    "url": "https://www.investopedia.com/terms/r/request-for-proposal.asp",
    "col": 3,
    "rowInCol": 9,
    "row": 11
  },
  {
    "a": "B2B",
    "f": "Business to Business",
    "cat": "business",
    "es": "Modelo donde una empresa vende productos o servicios a otras empresas (ej. mayoristas, software SaaS).",
    "en": "A model where a company sells products or services to other businesses (e.g. wholesalers, SaaS).",
    "url": "https://www.investopedia.com/terms/b/btob.asp",
    "col": 4,
    "rowInCol": 0,
    "row": 2
  },
  {
    "a": "B2C",
    "f": "Business to Consumer",
    "cat": "business",
    "es": "Modelo donde una empresa vende directamente al consumidor final (ej. Amazon, supermercados).",
    "en": "A model where a company sells directly to the end consumer (e.g. Amazon, supermarkets).",
    "url": "https://www.investopedia.com/terms/b/btoc.asp",
    "col": 4,
    "rowInCol": 1,
    "row": 3
  },
  {
    "a": "B2G",
    "f": "Business to Government",
    "cat": "business",
    "es": "Modelo donde empresas venden productos o servicios a instituciones gubernamentales o administración pública.",
    "en": "A model where companies sell products or services to government institutions or public administration.",
    "url": "https://www.investopedia.com/terms/b/btog.asp",
    "col": 4,
    "rowInCol": 2,
    "row": 4
  },
  {
    "a": "B2E",
    "f": "Business to Employee",
    "cat": "business",
    "es": "Estrategias o servicios internos de la empresa dirigidos a sus propios empleados (ej. portales de beneficios).",
    "en": "Internal company strategies or services directed at its own employees (e.g. benefits portals).",
    "url": "https://www.techtarget.com/searchcustomerexperience/definition/business-to-employee-B2E",
    "col": 4,
    "rowInCol": 3,
    "row": 5
  },
  {
    "a": "B2B2C",
    "f": "Business to Business to Consumer",
    "cat": "business",
    "es": "Una empresa usa otra empresa como intermediaria para llegar al consumidor final, compartiendo valor en la cadena.",
    "en": "A company uses another business as an intermediary to reach the end consumer, sharing value in the chain.",
    "url": "https://www.investopedia.com/terms/b/business-to-business-to-consumer-b2b2c.asp",
    "col": 4,
    "rowInCol": 4,
    "row": 6
  },
  {
    "a": "C2C",
    "f": "Consumer to Consumer",
    "cat": "business",
    "es": "Consumidores que venden a otros consumidores, generalmente en plataformas de segunda mano (ej. eBay, Vinted).",
    "en": "Consumers selling to other consumers, typically on second-hand platforms (e.g. eBay, Vinted).",
    "url": "https://www.investopedia.com/terms/c/ctoc.asp",
    "col": 4,
    "rowInCol": 5,
    "row": 7
  },
  {
    "a": "C2B",
    "f": "Consumer to Business",
    "cat": "business",
    "es": "Consumidores que ofrecen productos o servicios a empresas (ej. influencers, freelancers que proponen colaboraciones).",
    "en": "Consumers offering products or services to companies (e.g. influencers, freelancers proposing collaborations).",
    "url": "https://www.investopedia.com/terms/c/ctob.asp",
    "col": 4,
    "rowInCol": 6,
    "row": 8
  },
  {
    "a": "G2C",
    "f": "Government to Consumer",
    "cat": "business",
    "es": "Servicios ofrecidos por el gobierno directamente al ciudadano (ej. pago de impuestos online, trámites digitales).",
    "en": "Services offered by the government directly to citizens (e.g. online tax payments, digital procedures).",
    "url": "https://www.techtarget.com/searchcio/definition/G2C",
    "col": 4,
    "rowInCol": 7,
    "row": 9
  },
  {
    "a": "UX",
    "f": "User Experience",
    "cat": "ux",
    "es": "Experiencia global del usuario al interactuar con un producto o servicio.",
    "en": "The overall experience a user has when interacting with a product or service.",
    "url": "https://www.nngroup.com/articles/definition-user-experience/",
    "col": 5,
    "rowInCol": 0,
    "row": 2
  },
  {
    "a": "UI",
    "f": "User Interface",
    "cat": "ux",
    "es": "Conjunto de elementos visuales a través de los cuales el usuario interactúa con el producto.",
    "en": "The set of visual elements through which a user interacts with a product.",
    "url": "https://www.nngroup.com/articles/definition-user-interface/",
    "col": 5,
    "rowInCol": 1,
    "row": 3
  },
  {
    "a": "IA",
    "f": "Information Architecture",
    "cat": "ux",
    "es": "Organización y estructura del contenido para facilitar la navegación del usuario.",
    "en": "The organization and structure of content to facilitate user navigation.",
    "url": "https://www.nngroup.com/articles/ia-vs-navigation/",
    "col": 5,
    "rowInCol": 2,
    "row": 4
  },
  {
    "a": "CTA",
    "f": "Call to Action",
    "cat": "ux",
    "es": "Elemento de UI que invita al usuario a realizar una acción específica.",
    "en": "A UI element that prompts the user to take a specific action.",
    "url": "https://www.nngroup.com/articles/call-to-action-buttons/",
    "col": 5,
    "rowInCol": 3,
    "row": 5
  },
  {
    "a": "UXR",
    "f": "User Experience Research",
    "cat": "ux",
    "es": "Proceso de investigar el comportamiento y necesidades de usuarios para informar el diseño.",
    "en": "The process of researching user behavior and needs to inform design decisions.",
    "url": "https://www.nngroup.com/articles/ux-research-cheat-sheet/",
    "col": 5,
    "rowInCol": 4,
    "row": 6
  },
  {
    "a": "IxD",
    "f": "Interaction Design",
    "cat": "ux",
    "es": "Disciplina que define la estructura y el comportamiento de sistemas interactivos para crear interfaces fluidas.",
    "en": "Discipline defining the structure and behavior of interactive systems to create fluid interfaces.",
    "url": "https://www.interaction-design.org/literature/topics/interaction-design",
    "col": 5,
    "rowInCol": 5,
    "row": 7
  },
  {
    "a": "SUS",
    "f": "System Usability Scale",
    "cat": "ux",
    "es": "Encuesta de 10 preguntas para evaluar la usabilidad y facilidad de uso de un producto de forma rápida.",
    "en": "A 10-question survey for quickly evaluating the usability and user-friendliness of a product.",
    "url": "https://www.usability.gov/how-to-and-tools/methods/system-usability-scale.html",
    "col": 5,
    "rowInCol": 6,
    "row": 8
  },
  {
    "a": "WAI",
    "f": "Web Accessibility Initiative",
    "cat": "ux",
    "es": "Iniciativa del W3C para mejorar la accesibilidad web a personas con discapacidad, con estándares como WCAG.",
    "en": "A W3C initiative to improve web accessibility for people with disabilities, including WCAG.",
    "url": "https://www.w3.org/WAI/fundamentals/accessibility-intro/",
    "col": 5,
    "rowInCol": 7,
    "row": 9
  },
  {
    "a": "DS",
    "f": "Design System",
    "cat": "ux",
    "es": "Colección de componentes reutilizables, guías y estándares que garantizan consistencia visual y funcional en un producto.",
    "en": "A collection of reusable components, guidelines, and standards that ensure visual and functional consistency across a product.",
    "url": "https://www.nngroup.com/articles/design-systems-101/",
    "col": 5,
    "rowInCol": 8,
    "row": 10
  },
  {
    "a": "DLS",
    "f": "Design Language System",
    "cat": "ux",
    "es": "Sistema de diseño popularizado por Airbnb que unifica el lenguaje visual y de interacción de una marca en todos sus productos.",
    "en": "A design system popularized by Airbnb that unifies the visual and interaction language of a brand across all its products.",
    "url": "https://airbnb.design/building-a-visual-language/",
    "col": 5,
    "rowInCol": 9,
    "row": 11
  },
  {
    "a": "UI Kit",
    "f": "User Interface Kit",
    "cat": "ux",
    "es": "Biblioteca de componentes de interfaz lista para usar en herramientas como Figma, que acelera el diseño y mantiene consistencia.",
    "en": "A library of ready-to-use interface components in tools like Figma, speeding up design and maintaining consistency.",
    "url": "https://www.figma.com/resource-library/ui-kit/",
    "col": 5,
    "rowInCol": 10,
    "row": 12
  },
  {
    "a": "CI/CD",
    "f": "Continuous Integration / Continuous Deployment",
    "cat": "dev",
    "es": "Prácticas para automatizar la integración y entrega continua de software.",
    "en": "Practices for automating the continuous integration and delivery of software.",
    "url": "https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment",
    "col": 6,
    "rowInCol": 0,
    "row": 2
  },
  {
    "a": "SDK",
    "f": "Software Development Kit",
    "cat": "dev",
    "es": "Conjunto de herramientas para que desarrolladores creen apps sobre una plataforma.",
    "en": "A set of tools that allows developers to build apps on top of a platform.",
    "url": "https://www.ibm.com/topics/sdk",
    "col": 6,
    "rowInCol": 1,
    "row": 3
  },
  {
    "a": "IDE",
    "f": "Integrated Development Environment",
    "cat": "dev",
    "es": "Entorno que combina editor, compilador y debugger en una sola herramienta.",
    "en": "An environment combining a code editor, compiler, and debugger in one tool.",
    "url": "https://www.codecademy.com/article/what-is-an-ide",
    "col": 6,
    "rowInCol": 2,
    "row": 4
  },
  {
    "a": "TDD",
    "f": "Test-Driven Development",
    "cat": "dev",
    "es": "Metodología donde se escriben pruebas antes de escribir el código funcional.",
    "en": "A methodology where tests are written before the functional code.",
    "url": "https://martinfowler.com/bliki/TestDrivenDevelopment.html",
    "col": 6,
    "rowInCol": 3,
    "row": 5
  },
  {
    "a": "PWA",
    "f": "Progressive Web Application",
    "cat": "dev",
    "es": "Web app que usa tecnologías modernas para ofrecer experiencia similar a una app nativa.",
    "en": "A web app using modern technologies to deliver a native app-like experience.",
    "url": "https://web.dev/articles/what-are-pwas",
    "col": 6,
    "rowInCol": 4,
    "row": 6
  },
  {
    "a": "QA",
    "f": "Quality Assurance",
    "cat": "dev",
    "es": "Proceso de prueba y verificación que asegura que un producto cumple los estándares de calidad antes del lanzamiento.",
    "en": "The testing and verification process ensuring a product meets quality standards before release.",
    "url": "https://www.atlassian.com/incident-management/devops/qa",
    "col": 6,
    "rowInCol": 5,
    "row": 7
  },
  {
    "a": "DOD",
    "f": "Definition of Done",
    "cat": "dev",
    "es": "Acuerdo del equipo que define qué criterios debe cumplir una tarea para considerarse completada.",
    "en": "A team agreement defining what criteria a task must meet to be considered complete.",
    "url": "https://www.scrum.org/resources/blog/done-understanding-definition-done",
    "col": 6,
    "rowInCol": 6,
    "row": 8
  },
  {
    "a": "API",
    "f": "Application Programming Interface",
    "cat": "tech",
    "es": "Interfaz que permite que dos aplicaciones se comuniquen entre sí.",
    "en": "An interface that allows two applications to communicate with each other.",
    "url": "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction",
    "col": 7,
    "rowInCol": 0,
    "row": 2
  },
  {
    "a": "JSON",
    "f": "JavaScript Object Notation",
    "cat": "tech",
    "es": "Formato ligero de intercambio de datos legible por humanos y máquinas.",
    "en": "A lightweight data interchange format readable by both humans and machines.",
    "url": "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON",
    "col": 7,
    "rowInCol": 1,
    "row": 3
  },
  {
    "a": "XML",
    "f": "Extensible Markup Language",
    "cat": "tech",
    "es": "Lenguaje de marcado para almacenar y transportar datos de forma estructurada.",
    "en": "A markup language for storing and transporting data in a structured format.",
    "url": "https://developer.mozilla.org/en-US/docs/Web/XML/XML_introduction",
    "col": 7,
    "rowInCol": 2,
    "row": 4
  },
  {
    "a": "REST",
    "f": "Representational State Transfer",
    "cat": "tech",
    "es": "Estilo arquitectónico para diseñar APIs web basado en HTTP.",
    "en": "An architectural style for designing web APIs based on HTTP.",
    "url": "https://restfulapi.net/",
    "col": 7,
    "rowInCol": 3,
    "row": 5
  },
  {
    "a": "SOAP",
    "f": "Simple Object Access Protocol",
    "cat": "tech",
    "es": "Protocolo de mensajería basado en XML para intercambio de información entre sistemas.",
    "en": "An XML-based messaging protocol for exchanging information between systems.",
    "url": "https://www.ibm.com/topics/soap-apis",
    "col": 7,
    "rowInCol": 4,
    "row": 6
  },
  {
    "a": "SaaS",
    "f": "Software as a Service",
    "cat": "tech",
    "es": "Modelo donde el software se accede vía internet como servicio, sin instalación local.",
    "en": "A model where software is accessed over the internet as a service, no local install.",
    "url": "https://www.salesforce.com/saas/",
    "col": 7,
    "rowInCol": 5,
    "row": 7
  },
  {
    "a": "DBMS",
    "f": "Database Management System",
    "cat": "tech",
    "es": "Software para crear, gestionar y consultar bases de datos estructuradas.",
    "en": "Software used to create, manage, and query structured databases.",
    "url": "https://www.oracle.com/database/what-is-database/",
    "col": 7,
    "rowInCol": 6,
    "row": 8
  },
  {
    "a": "AI",
    "f": "Artificial Intelligence",
    "cat": "tech",
    "es": "Tecnología que permite a los sistemas aprender y razonar. En diseño se aplica a interfaces adaptativas y chatbots.",
    "en": "Technology enabling systems to learn and reason. In design, applied to adaptive UIs and chatbots.",
    "url": "https://www.ibm.com/topics/artificial-intelligence",
    "col": 7,
    "rowInCol": 7,
    "row": 9
  },
  {
    "a": "ML",
    "f": "Machine Learning",
    "cat": "tech",
    "es": "Rama de la IA que permite a los sistemas aprender de datos y mejorar sin ser programados explícitamente.",
    "en": "A branch of AI that allows systems to learn from data and improve without explicit programming.",
    "url": "https://www.ibm.com/topics/machine-learning",
    "col": 7,
    "rowInCol": 8,
    "row": 10
  },
  {
    "a": "IoT",
    "f": "Internet of Things",
    "cat": "tech",
    "es": "Red de dispositivos físicos conectados a internet que recopilan e intercambian datos.",
    "en": "A network of physical devices connected to the internet that collect and exchange data.",
    "url": "https://www.ibm.com/topics/internet-of-things",
    "col": 7,
    "rowInCol": 9,
    "row": 11
  },
  {
    "a": "CMS",
    "f": "Content Management System",
    "cat": "tech",
    "es": "Plataforma para crear, gestionar y publicar contenido digital sin necesidad de programar.",
    "en": "A platform for creating, managing, and publishing digital content without coding.",
    "url": "https://www.cloudflare.com/learning/performance/what-is-a-content-management-system/",
    "col": 7,
    "rowInCol": 10,
    "row": 12
  },
  {
    "a": "CSS",
    "f": "Cascading Style Sheets",
    "cat": "design",
    "es": "Lenguaje para definir el estilo visual de páginas web: colores, tipografía, espaciado y layout.",
    "en": "A language for defining the visual style of web pages: colors, typography, spacing, and layout.",
    "url": "https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS",
    "col": 8,
    "rowInCol": 0,
    "row": 2
  },
  {
    "a": "HTML",
    "f": "HyperText Markup Language",
    "cat": "design",
    "es": "Lenguaje estándar para crear la estructura y el contenido de páginas web.",
    "en": "The standard language for creating the structure and content of web pages.",
    "url": "https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML",
    "col": 8,
    "rowInCol": 1,
    "row": 3
  },
  {
    "a": "SVG",
    "f": "Scalable Vector Graphics",
    "cat": "design",
    "es": "Formato vectorial que escala sin perder calidad, ideal para iconos, logos y gráficos en cualquier resolución.",
    "en": "A vector format that scales without losing quality, ideal for icons, logos, and graphics.",
    "url": "https://developer.mozilla.org/en-US/docs/Web/SVG",
    "col": 8,
    "rowInCol": 2,
    "row": 4
  },
  {
    "a": "PNG",
    "f": "Portable Network Graphics",
    "cat": "design",
    "es": "Formato de imagen de alta calidad sin pérdida, ideal para fondos transparentes y gráficos detallados.",
    "en": "A high-quality lossless image format ideal for transparent backgrounds and detailed graphics.",
    "url": "https://www.adobe.com/creativecloud/file-types/image/raster/png-file.html",
    "col": 8,
    "rowInCol": 3,
    "row": 5
  },
  {
    "a": "GIF",
    "f": "Graphics Interchange Format",
    "cat": "design",
    "es": "Formato de imagen que soporta animaciones simples y transparencia, usado para micro-interacciones.",
    "en": "An image format supporting simple animations and transparency, used for micro-interactions.",
    "url": "https://www.adobe.com/creativecloud/file-types/image/raster/gif-file.html",
    "col": 8,
    "rowInCol": 4,
    "row": 6
  },
  {
    "a": "DPI",
    "f": "Dots Per Inch",
    "cat": "design",
    "es": "Medida de densidad de imagen que determina su resolución. A mayor DPI, mayor nitidez en pantalla o impresión.",
    "en": "An image density measure that determines resolution. Higher DPI means sharper output.",
    "url": "https://www.adobe.com/creativecloud/photography/discover/dots-per-inch.html",
    "col": 8,
    "rowInCol": 5,
    "row": 7
  },
  {
    "a": "RWD",
    "f": "Responsive Web Design",
    "cat": "design",
    "es": "Enfoque de diseño web que asegura que las páginas se vean bien en cualquier dispositivo o tamaño de pantalla.",
    "en": "A web design approach ensuring pages look great on any device or screen size.",
    "url": "https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design",
    "col": 8,
    "rowInCol": 6,
    "row": 8
  },
  {
    "a": "AR/VR",
    "f": "Augmented Reality / Virtual Reality",
    "cat": "design",
    "es": "Tecnologías que superponen o reemplazan la realidad con contenido digital, usadas en experiencias inmersivas.",
    "en": "Technologies that overlay or replace reality with digital content for immersive experiences.",
    "url": "https://www.interaction-design.org/literature/topics/augmented-reality",
    "col": 8,
    "rowInCol": 7,
    "row": 9
  },
  {
    "a": "CX",
    "f": "Customer Experience",
    "cat": "experience",
    "es": "Suma de todas las interacciones y percepciones que un cliente tiene con una marca, del primer contacto al soporte.",
    "en": "The sum of all interactions and perceptions a customer has with a brand, from first contact to support.",
    "url": "https://www.nngroup.com/articles/ux-vs-cx/",
    "col": 9,
    "rowInCol": 0,
    "row": 0
  },
  {
    "a": "BX",
    "f": "Brand Experience",
    "cat": "experience",
    "es": "Percepción emocional del usuario hacia una marca en todos sus puntos de contacto, digitales y físicos.",
    "en": "The user's emotional perception of a brand across all its touchpoints, digital and physical.",
    "url": "https://www.interaction-design.org/literature/article/brand-experience",
    "col": 9,
    "rowInCol": 1,
    "row": 1
  },
  {
    "a": "SD",
    "f": "Service Design",
    "cat": "experience",
    "es": "Disciplina que diseña todos los puntos de contacto de un servicio, incluyendo personas, procesos y canales.",
    "en": "A discipline that designs all touchpoints of a service, including people, processes, and channels.",
    "url": "https://www.interaction-design.org/literature/topics/service-design",
    "col": 9,
    "rowInCol": 2,
    "row": 2
  },
  {
    "a": "CRM",
    "f": "Customer Relationship Management",
    "cat": "experience",
    "es": "Sistema para gestionar y analizar interacciones con clientes, con el fin de mejorar relaciones y retención.",
    "en": "A system to manage and analyze customer interactions to improve relationships and increase retention.",
    "url": "https://www.salesforce.com/crm/what-is-crm/",
    "col": 9,
    "rowInCol": 3,
    "row": 3
  },
  {
    "a": "UCP",
    "f": "Unified Customer Profile",
    "cat": "experience",
    "es": "Representación centralizada de todos los datos de un cliente en un solo registro, para personalizar experiencias.",
    "en": "A centralized record of all data about a customer, used to personalize their experience.",
    "url": "https://www.techtarget.com/searchcustomerexperience/definition/unified-customer-profile",
    "col": 9,
    "rowInCol": 4,
    "row": 4
  },
  {
    "a": "CJM",
    "f": "Customer Journey Mapping",
    "cat": "experience",
    "es": "Mapa visual de la experiencia del cliente que refleja sus metas, emociones e interacciones con el producto.",
    "en": "A visual map of the customer experience reflecting goals, emotions, and touchpoints over time.",
    "url": "https://www.nngroup.com/articles/customer-journey-mapping/",
    "col": 9,
    "rowInCol": 5,
    "row": 5
  }
];

// Periodic-table grid dimensions
window.PT_LAYOUT = {
  cols: 10,
  rows: 13,
};

window.CATS = {
  core:       { label:{es:'Core Product',     en:'Core Product'},     bg:'#8343cf', text:'#f0e8ff' },
  metrics:    { label:{es:'Métricas',         en:'Metrics'},          bg:'#f58b61', text:'#3d1800' },
  business:   { label:{es:'Negocio',          en:'Business'},         bg:'#4aebdb', text:'#003330' },
  ux:         { label:{es:'Diseño UX',        en:'UX Design'},        bg:'#f4d604', text:'#2a2200' },
  dev:        { label:{es:'Desarrollo',       en:'Development'},      bg:'#f03b72', text:'#fff0f4' },
  tech:       { label:{es:'Tecnología',       en:'Technology'},       bg:'#3492ea', text:'#e8f2ff' },
  design:     { label:{es:'Diseño Visual',    en:'Visual Design'},    bg:'#f980e9', text:'#3a0035' },
  experience: { label:{es:'Experiencia CX',   en:'Experience CX'},    bg:'#3831df', text:'#e8e6ff' },
};
